### ISSUE TITLE
Segmentation fault when using ``casadi.repmat()`` with a first argument ``None``

### ISSUE THREAD

**Issue by adbuerger** [casadi/casadi#1380]
I wanted to use ``casadi.repmat()`` inside a try-except-clause, with possibility for ``repmat()`` to recieve ``None`` as a first argument. Instead of throwing an error message that can be caught, a segmentation fault that crashes Python is produced:

```python
In [1]: import casadi as ca
In [2]: ca.repmat(None, 1, 1)

[1]    12425 segmentation fault (core dumped)  ipython --matplotlib
```

I reported this because I do no think that this behaviour is intended, though it might be a bad idea to call ``repmat()`` in that way.

**Comment by jgillis** [comment]
Thanks for reporting!

Can you confirm that this is fixed in our fresh 2.3.0-rc2 release?

**Comment by adbuerger** [comment]
With the latest version, a ``ValueError`` is thrown. I'm sorry, I thought I was using the latest version. I will close the issue, thank you for your very quick answer!

**Comment by jgillis** [comment]
You are certainly not to blame; the release was minutes ago ;-)

**Comment by adbuerger** [comment]
I'm sorry, I have to reopen the issue, because the error still appears with the following scenario (which like this would happen within my actual code):

```python
import casadi as ca
import pylab as pl
a = None
b = pl.atleast_2d(None)
c = ca.repmat(b, 1, 1)
```

**Comment by jgillis** [comment]
This is patched now and scheduled for inclusion in 2.3.0.
Thanks again for your diligent reporting!
